[package]
name = "memegen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.25"
reqwest = { version = "0.12", features = ["blocking"] }
anyhow = "1.0"
